In [1]:
import numpy as np

In [2]:
list_example = [3, 41, 4, 6, 43]

In [3]:
array_example = np.array(list_example)

In [4]:
print(array_example)

[ 3 41  4  6 43]


In [5]:
array_example += 5

In [6]:
print(array_example)

[ 8 46  9 11 48]


In [7]:
array_example[:] = 5
print(array_example)

[5 5 5 5 5]


In [8]:
array_example = np.array(list_example)
print(array_example)

[ 3 41  4  6 43]


In [9]:
farenheit_array = array_example*9/5+32

In [10]:
print(farenheit_array)

[ 37.4 105.8  39.2  42.8 109.4]


In [11]:
print(farenheit_array >= 80)

[False  True False False  True]


In [14]:
print((farenheit_array >= 80) | (farenheit_array < 40))

[ True  True  True False  True]


In [15]:
remainder_array = array_example % 2
print(remainder_array)

[1 1 0 0 1]


In [16]:
print(array_example %2 == 0)

[False False  True  True False]


In [17]:
one_d_array_example = np.array(list_example)

In [18]:
list_of_lists = [[0,1,2],[3,4,5],[6,7,8]]

In [19]:
two_d_array_example = np.array(list_of_lists)
print(two_d_array_example)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
array_with_zeros = np.zeros((3, 5))
print(array_with_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
array_with_ones = np.ones((4, 3), dtype=int)
print(array_with_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [25]:
odd_array = np.arange(3, 32, 2)
print(odd_array)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]


In [26]:
odd_array.shape = (5,3)
print(odd_array)

[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]
 [21 23 25]
 [27 29 31]]


In [33]:
np.linspace(5, 50, num = 10, endpoint=True, dtype=int)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [34]:
three_d_array = np.arange(40)
three_d_array.shape = (2, 5, 4)
print(three_d_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]]


In [35]:
print(np.arange(2, 101, 2))

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [36]:
print(np.linspace(2, 100, num=50, endpoint=True, dtype=int))

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [37]:
print(odd_array.ndim)

2


In [38]:
print(odd_array.shape)
print(odd_array.size)
print(odd_array.dtype)

(5, 3)
15
int64


In [39]:
print(len(odd_array.shape))

2


In [40]:
print(np.prod(odd_array.shape))

15


In [41]:
print(odd_array)
print(odd_array.sum())

[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]
 [21 23 25]
 [27 29 31]]
255


In [42]:
print(odd_array.sum(axis=0))

[75 85 95]


In [44]:
print(odd_array.sum(axis=1))

[15 33 51 69 87]


In [46]:
print(one_d_array_example.sum())

97


In [47]:
print(one_d_array_example.sum(axis=0))

97


In [48]:
odd_array_num_columns = odd_array.shape[1]
print(odd_array_num_columns)

3


In [49]:
print(odd_array.max(axis=1)-odd_array.min(axis=1))

[4 4 4 4 4]


In [52]:
print((odd_array.max(axis=0))-(odd_array.min(axis=0)))

[24 24 24]


In [53]:
log_odd_array = np.log(odd_array)
print(log_odd_array)

[[1.09861229 1.60943791 1.94591015]
 [2.19722458 2.39789527 2.56494936]
 [2.7080502  2.83321334 2.94443898]
 [3.04452244 3.13549422 3.21887582]
 [3.29583687 3.36729583 3.4339872 ]]


In [54]:
random_array = np.random.rand(12, 6)

In [55]:
print(random_array)

[[0.84818481 0.51037355 0.37428532 0.57858941 0.38419875 0.97480171]
 [0.58104094 0.14225202 0.59633308 0.75058864 0.18240927 0.92889103]
 [0.14177508 0.3337997  0.86898655 0.77376029 0.3609023  0.15820487]
 [0.5400602  0.52434725 0.09985424 0.46303886 0.71163441 0.36549471]
 [0.80531448 0.1482564  0.99704611 0.53529687 0.96212237 0.13337527]
 [0.29847001 0.65151039 0.81133595 0.80877087 0.7727192  0.62244315]
 [0.0305554  0.91783974 0.01062671 0.87535324 0.82644456 0.6488469 ]
 [0.04261794 0.73526986 0.65064146 0.79269738 0.47356146 0.65101092]
 [0.08545473 0.50270763 0.79807212 0.82338002 0.37480973 0.02470045]
 [0.95892041 0.05603929 0.23441853 0.01649116 0.10593145 0.79023771]
 [0.86272466 0.19377593 0.84819038 0.75188417 0.45668851 0.94149462]
 [0.05834983 0.95187777 0.84391951 0.7876191  0.42185405 0.09800767]]


In [57]:
print(random_array[3:5, 1:3])

[[0.52434725 0.09985424]
 [0.1482564  0.99704611]]


In [58]:
print(random_array[:,:-1])

[[0.84818481 0.51037355 0.37428532 0.57858941 0.38419875]
 [0.58104094 0.14225202 0.59633308 0.75058864 0.18240927]
 [0.14177508 0.3337997  0.86898655 0.77376029 0.3609023 ]
 [0.5400602  0.52434725 0.09985424 0.46303886 0.71163441]
 [0.80531448 0.1482564  0.99704611 0.53529687 0.96212237]
 [0.29847001 0.65151039 0.81133595 0.80877087 0.7727192 ]
 [0.0305554  0.91783974 0.01062671 0.87535324 0.82644456]
 [0.04261794 0.73526986 0.65064146 0.79269738 0.47356146]
 [0.08545473 0.50270763 0.79807212 0.82338002 0.37480973]
 [0.95892041 0.05603929 0.23441853 0.01649116 0.10593145]
 [0.86272466 0.19377593 0.84819038 0.75188417 0.45668851]
 [0.05834983 0.95187777 0.84391951 0.7876191  0.42185405]]


In [59]:
print(random_array[:,-1:])

[[0.97480171]
 [0.92889103]
 [0.15820487]
 [0.36549471]
 [0.13337527]
 [0.62244315]
 [0.6488469 ]
 [0.65101092]
 [0.02470045]
 [0.79023771]
 [0.94149462]
 [0.09800767]]


In [60]:
print(random_array[3:5, 1:3].mean())

0.4423760028744994


In [61]:
three_d_array[1:2, 2:4, :2] = 10

In [62]:
print(three_d_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [10 10 30 31]
  [10 10 34 35]
  [36 37 38 39]]]


In [63]:
three_d_array[1:2, 2:4, :2] = three_d_array[1:2, 2:4, :2]/2
print(three_d_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [ 5  5 30 31]
  [ 5  5 34 35]
  [36 37 38 39]]]


In [64]:
random_array[3:5, 2:3] = random_array[3:5, 2:3].mean()

In [65]:
bol_array = random_array >= 0.5
print(bol_array)

[[ True  True False  True False  True]
 [ True False  True  True False  True]
 [False False  True  True False False]
 [ True  True  True False  True False]
 [ True False  True  True  True False]
 [False  True  True  True  True  True]
 [False  True False  True  True  True]
 [False  True  True  True False  True]
 [False  True  True  True False False]
 [ True False False False False  True]
 [ True False  True  True False  True]
 [False  True  True  True False False]]


In [66]:
print(random_array[bol_array])

[0.84818481 0.51037355 0.57858941 0.97480171 0.58104094 0.59633308
 0.75058864 0.92889103 0.86898655 0.77376029 0.5400602  0.52434725
 0.54845018 0.71163441 0.80531448 0.54845018 0.53529687 0.96212237
 0.65151039 0.81133595 0.80877087 0.7727192  0.62244315 0.91783974
 0.87535324 0.82644456 0.6488469  0.73526986 0.65064146 0.79269738
 0.65101092 0.50270763 0.79807212 0.82338002 0.95892041 0.79023771
 0.86272466 0.84819038 0.75188417 0.94149462 0.95187777 0.84391951
 0.7876191 ]


In [67]:
print(random_array[random_array >= 0.5])

[0.84818481 0.51037355 0.57858941 0.97480171 0.58104094 0.59633308
 0.75058864 0.92889103 0.86898655 0.77376029 0.5400602  0.52434725
 0.54845018 0.71163441 0.80531448 0.54845018 0.53529687 0.96212237
 0.65151039 0.81133595 0.80877087 0.7727192  0.62244315 0.91783974
 0.87535324 0.82644456 0.6488469  0.73526986 0.65064146 0.79269738
 0.65101092 0.50270763 0.79807212 0.82338002 0.95892041 0.79023771
 0.86272466 0.84819038 0.75188417 0.94149462 0.95187777 0.84391951
 0.7876191 ]


In [68]:
print(random_array[bol_array].min())

0.5027076317161814


In [69]:
random_array[random_array > np.percentile(random_array, 90)] = np.percentile(random_array, 90)

In [70]:
print(random_array)

[[0.84818481 0.51037355 0.37428532 0.57858941 0.38419875 0.87471657]
 [0.58104094 0.14225202 0.59633308 0.75058864 0.18240927 0.87471657]
 [0.14177508 0.3337997  0.86898655 0.77376029 0.3609023  0.15820487]
 [0.5400602  0.52434725 0.54845018 0.46303886 0.71163441 0.36549471]
 [0.80531448 0.1482564  0.54845018 0.53529687 0.87471657 0.13337527]
 [0.29847001 0.65151039 0.81133595 0.80877087 0.7727192  0.62244315]
 [0.0305554  0.87471657 0.01062671 0.87471657 0.82644456 0.6488469 ]
 [0.04261794 0.73526986 0.65064146 0.79269738 0.47356146 0.65101092]
 [0.08545473 0.50270763 0.79807212 0.82338002 0.37480973 0.02470045]
 [0.87471657 0.05603929 0.23441853 0.01649116 0.10593145 0.79023771]
 [0.86272466 0.19377593 0.84819038 0.75188417 0.45668851 0.87471657]
 [0.05834983 0.87471657 0.84391951 0.7876191  0.42185405 0.09800767]]


In [71]:
random_array_two = np.random.rand(12,6)
random_array_two_copy = random_array_two

In [72]:
random_array_two = np.where(random_array_two >= random_array_two.mean(), 1, 0)

In [73]:
print(random_array_two)

[[0 0 1 1 0 1]
 [1 1 0 0 1 1]
 [0 1 0 0 0 1]
 [1 0 1 0 0 1]
 [0 1 0 0 1 0]
 [1 1 0 0 0 0]
 [1 1 1 1 0 0]
 [0 0 0 1 0 0]
 [1 0 1 0 0 1]
 [1 1 1 0 0 1]
 [1 1 0 1 0 1]
 [0 1 1 1 1 1]]


In [74]:
random_array_two_copy[random_array_two_copy >= random_array_two_copy.mean()] = 1
random_array_two_copy[random_array_two_copy < random_array_two_copy.mean()] = 0
random_array_two_copy = random_array_two_copy.astype(int)
print(random_array_two_copy)

[[0 0 1 1 0 1]
 [1 1 0 0 1 1]
 [0 1 0 0 0 1]
 [1 0 1 0 0 1]
 [0 1 0 0 1 0]
 [1 1 0 0 0 0]
 [1 1 1 1 0 0]
 [0 0 0 1 0 0]
 [1 0 1 0 0 1]
 [1 1 1 0 0 1]
 [1 1 0 1 0 1]
 [0 1 1 1 1 1]]


In [75]:
random_array_three = np.random.rand(12,6)

In [76]:
random_array_three = np.where(random_array_three >= np.percentile(random_array_three, 90), np.percentile(random_array_three, 90), np.where(random_array_three <= np.percentile(random_array_three, 10), np.percentile(random_array_three, 10), random_array_three))
print(random_array_three)

[[0.36712927 0.27809992 0.48559744 0.85224441 0.84476096 0.40651622]
 [0.38477517 0.24835006 0.85224441 0.33685779 0.40250036 0.63494204]
 [0.19417174 0.72969251 0.19329535 0.56467035 0.79107249 0.69120006]
 [0.24575724 0.19329535 0.19329535 0.77387908 0.37132474 0.80487227]
 [0.49302621 0.85224441 0.6626415  0.5302688  0.77851545 0.7951708 ]
 [0.19329535 0.85224441 0.63473081 0.40709364 0.54214508 0.78020113]
 [0.60292399 0.66803221 0.27129451 0.19329535 0.57965819 0.85224441]
 [0.72768734 0.37787047 0.85224441 0.52128683 0.39569162 0.42964451]
 [0.49942324 0.4876123  0.33355039 0.82043419 0.62603675 0.85224441]
 [0.52701267 0.58407452 0.32415525 0.56527129 0.38317399 0.82469419]
 [0.26842298 0.19329535 0.39535558 0.58949328 0.61365943 0.19329535]
 [0.56575768 0.72896392 0.20034508 0.19329535 0.56493677 0.85224441]]


In [77]:
student_course_scores = [85,90,75,83,68]

student_course_grades = []